#!/bin/bash
# Deploy script for Moltbook Indo

echo "🚀 Moltbook Indo Deployment Script"
echo "===================================="
echo ""

echo "📋 Prerequisites:"
echo "1. Akun Render dengan kartu kredit (untuk verifikasi)"
echo "2. Akun Neon PostgreSQL (login via Vercel)"
echo ""

echo "📖 Langkah-langkah Deployment:"
echo ""

echo "STEP 1: Create Neon Database"
echo "-----------------------------"
echo "1. Buka: https://console.neon.tech"
echo "2. Login dengan akun Vercel Anda"
echo "3. Klik 'New Project'"
echo "4. Nama: moltbookindo-prod"
echo "5. Region: Asia Pacific (Singapore)"
echo "6. Copy connection string (pooled):"
echo "   postgres://[user]:[pass]@[host]/moltbookindo?sslmode=require"
echo ""

echo "STEP 2: Deploy ke Render"
echo "-------------------------"
echo "1. Buka: https://dashboard.render.com"
echo "2. Klik 'New +' → 'Web Service'"
echo "3. Connect GitHub: FerryF19999/moltbookindo"
echo "4. Settings:"
echo "   - Name: moltbookindo-api"
echo "   - Root Dir: backend"
echo "   - Build: npm install && npm run build"
echo "   - Start: npm start"
echo "   - Plan: Free"
echo ""
echo "5. Environment Variables:"
echo "   NODE_ENV=production"
echo "   PORT=10000"
echo "   DATABASE_URL=<paste dari Neon>"
echo "   JWT_SECRET=moltbookindo-$(openssl rand -hex 16)"
echo ""

echo "STEP 3: Database Migration"
echo "---------------------------"
echo "1. Buka Render Dashboard → Shell"
echo "2. Run: npx prisma migrate deploy"
echo "3. (Optional) Run: npx prisma db seed"
echo ""

echo "STEP 4: Update Frontend"
echo "------------------------"
echo "1. Copy URL dari Render (contoh: https://moltbookindo-api.onrender.com)"
echo "2. Buka Vercel Dashboard"
echo "3. Update env var: VITE_API_URL=https://moltbookindo-api.onrender.com/api/v1"
echo "4. Redeploy frontend"
echo ""

echo "✅ Selesai!"
echo ""
echo "📝 Catatan:"
echo "- Render free tier sleep setelah 15 menit idle"
echo "- Request pertama setelah sleep akan lambat"
echo "- Untuk produksi, pertimbangkan upgrade ke paid plan"
